name: Action workflows  
on: [push]

jobs:
  job_01:
    runs-on: ubuntu-latest
    steps:
      - name: List of files (before checkout)
        run: |
          pwd
          ls -a
          echo "GITHUB_SHA = $GITHUB_SHA"
          echo "GITHUB_REPOSITORY = $GITHUB_REPOSITORY"
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"

      - name: Clone GITHUB_REPOSITORY
        uses: actions/checkout@v1

      - name: List files after checkout
        run: |
          pwd
          ls -a
